const statesMapper = [
    { code: "AN", name: "Andaman and Nicobar Islands", capital: "Port Blair" },
    { code: "AP", name: "Andhra Pradesh", capital: "Amaravati" },
    { code: "AR", name: "Arunachal Pradesh", capital: "Itanagar" },
    { code: "AS", name: "Assam", capital: "Dispur" },
    { code: "BR", name: "Bihar", capital: "Patna" },
    { code: "CH", name: "Chandigarh", capital: "Chandigarh" },
    { code: "CT", name: "Chhattisgarh", capital: "Raipur" },
    { code: "DN", name: "Dadra and Nagar Haveli and Daman and Diu", capital: "Daman" },
    { code: "DL", name: "Delhi", capital: "New Delhi" },
    { code: "GA", name: "Goa", capital: "Panaji" },
    { code: "GJ", name: "Gujarat", capital: "Gandhinagar" },
    { code: "HR", name: "Haryana", capital: "Chandigarh" },
    { code: "HP", name: "Himachal Pradesh", capital: "Shimla" },
    { code: "JK", name: "Jammu and Kashmir", capital: "Srinagar (Summer), Jammu (Winter)" },
    { code: "JH", name: "Jharkhand", capital: "Ranchi" },
    { code: "KA", name: "Karnataka", capital: "Bengaluru" },
    { code: "KL", name: "Kerala", capital: "Thiruvananthapuram" },
    { code: "LA", name: "Ladakh", capital: "Leh" },
    { code: "MP", name: "Madhya Pradesh", capital: "Bhopal" },
    { code: "MH", name: "Maharashtra", capital: "Mumbai" },
    { code: "MN", name: "Manipur", capital: "Imphal" },
    { code: "ML", name: "Meghalaya", capital: "Shillong" },
    { code: "MZ", name: "Mizoram", capital: "Aizawl" },
    { code: "NL", name: "Nagaland", capital: "Kohima" },
    { code: "OR", name: "Odisha", capital: "Bhubaneswar" },
    { code: "PY", name: "Puducherry", capital: "Puducherry" },
    { code: "PB", name: "Punjab", capital: "Chandigarh" },
    { code: "RJ", name: "Rajasthan", capital: "Jaipur" },
    { code: "SK", name: "Sikkim", capital: "Gangtok" },
    { code: "TN", name: "Tamil Nadu", capital: "Chennai" },
    { code: "TG", name: "Telangana", capital: "Hyderabad" },
    { code: "TR", name: "Tripura", capital: "Agartala" },
    { code: "UP", name: "Uttar Pradesh", capital: "Lucknow" },
    { code: "UT", name: "Uttarakhand", capital: "Dehradun" },
    { code: "WB", name: "West Bengal", capital: "Kolkata" }
];

export default statesMapper;
