const statesMapper = [
    { id: 0, name: "Andaman and Nicobar Islands" },
    { id: 1, name: "Andhra Pradesh" },
    { id: 2, name: "Arunachal Pradesh" },
    { id: 3, name: "Assam" },
    { id: 4, name: "Bihar" },
    { id: 5, name: "Chandigarh" },
    { id: 6, name: "Chhattisgarh" },
    { id: 7, name: "Dadra and Nagar Haveli and Daman and Diu" },
    { id: 8, name: "Delhi" },
    { id: 9, name: "Goa" },
    { id: 10, name: "Gujarat" },
    { id: 11, name: "Haryana" },
    { id: 12, name: "Himachal Pradesh" },
    { id: 13, name: "Jammu and Kashmir" },
    { id: 14, name: "Jharkhand" },
    { id: 15, name: "Karnataka" },
    { id: 16, name: "Kerala" },
    { id: 17, name: "Ladakh" },
    { id: 18, name: "Madhya Pradesh" },
    { id: 19, name: "Maharashtra" },
    { id: 20, name: "Manipur" },
    { id: 21, name: "Meghalaya" },
    { id: 22, name: "Mizoram" },
    { id: 23, name: "Nagaland" },
    { id: 24, name: "Odisha" },
    { id: 25, name: "Puducherry" },
    { id: 26, name: "Punjab" },
    { id: 27, name: "Rajasthan" },
    { id: 28, name: "Sikkim" },
    { id: 29, name: "Tamil Nadu" },
    { id: 30, name: "Telangana" },
    { id: 31, name: "Tripura" },
    { id: 32, name: "Uttar Pradesh" },
    { id: 33, name: "Uttarakhand" },
    { id: 34, name: "West Bengal" }
];


export default statesMapper;
